### ISSUE TITLE
x48: can't open /home/tom/.hp48/hp48

### ISSUE THREAD

**Issue by awesome14** [gwenhael-le-moine/x48#2]
What is hp48, a file, directory, what? Also have the message, "can't open rom.dump". I built the debian way. I have the rom in ~/.hp48/rom. How do I get 'rom.dump'? Where is it supposed to be? I download the rom from hpcalc.org.

**Comment by gwenhael-le-moine** [comment]
The roms are bundled with the sources in the ROMs directory.
What I do to use the most recent GX rom is to bunzip2 gxrom-r.bz2 into ~/.hp48, rename it to ~/.hp48/rom and symlink ~/.hp48.rom.dump to it

    $ mkdir -p ~/.hp48
    $ cp $SRC/ROMs/gxrom-r.bz2 ~/.hp48
    $ cd ~/.hp48
    $ bunzip2 gxrom-r.bz2
    $ mv gxrom-r rom
    $ ln -s rom rom.dump

finally you need to initialize x48:

    $ cd ~/.hp48 && x48 -initialize

You can have a look at how I package x48 for Slackware here: [https://github.com/gwenhael-le-moine/slackbuilds/blob/master/xap/x48/SlackBuild](https://github.com/gwenhael-le-moine/slackbuilds/blob/master/xap/x48/SlackBuild)

**Comment by awesome14** [comment]
I'll have a look at the slackware package.  I think the source package on sourceforge might need updating. I'll try here at github.

**Comment by awesome14** [comment]
Here's a patch for 2 edits I had to do in the configure script:

--- configure.bak       2018-06-09 08:09:05.153534601 -0400
+++ configure   2018-06-07 20:39:50.112273412 -0400
@@ -4186,7 +4186,7 @@
 X_LIBS="$X_LIBS -lX11"
 
 
-PKG_PROG_PKG_CONFIG(0.20)
+PKG_PROG_PKG_CONFIG\(0.20\)
 
 # ********* readline library
 # Check whether --enable-readline was given.
@@ -5366,7 +5366,7 @@
 done
 
 
-PKG_CHECK_MODULES(APPDEFS, xt)
+PKG_CHECK_MODULES\(APPDEFS, xt\)
 
 # Check whether --with-appdefaultdir was given.
 if test "${with_appdefaultdir+set}" = set; then :

**Comment by awesome14** [comment]
Well, the editor ruined my patch. The open paren was causing an error in configure, so I escaped both parens in both terms, and it completed.

**Comment by awesome14** [comment]
Here's a suggested debian/README.debian file:

x48 for Debian
--------------

To build the configure script execute ./autogen.sh.

To build the debian way 
debian/rules build.

mkdir -p ~/.hp48 

Copy one of the roms found in the ROMs directory to ~/.hp48.

cd ~/.hp48

Extract the rom file.

mv romfile rom

ln -s rom rom.dump

../x48/src/./x48 -initialize

When the emulator appears, hit the top 'f' key for 'no'.

Have fun!

Tom Kayser (forensic@milwpc.com) Sat. Jun. 9, 2018 09:06:25
